name: Run checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer validate --strict
      - run: composer install --prefer-dist
      - run: composer check